language: python
python:
- 3.9.12

install:
- pip install -r requirements.txt
- pip install black
- pip install flake8
- pip install coverage

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  # - black --check .
  # - flake8 .
  - coverage run --source=swe1-app manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: os.getenv('$ACCESS_KEY_ID')
  secret_access_key:
    secure: os.getenv('$SECRET_ACCESS_KEY')
  region: "us-west-2"
  app: "ebdjango-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-373206328898"
  on:
    all_branches: true